export const LOAD_FLIGHTS_REQUEST = 'LOAD_FLIGHTS_REQUEST'
export const LOAD_FLIGHTS_SUCCESS = 'LOAD_FLIGHTS_SUCCESS'
export const LOAD_FLIGHTS_FAILURE = 'LOAD_FLIGHTS_FAILURE'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'